### ISSUE TITLE
DTD test set performance

### ISSUE THREAD

**Issue by kasurashan** [nik-dim/tall_masks#1]
Hello.

Thank you for sharing this interesting research and the codes.

https://github.com/nik-dim/tall_masks/blob/db2488ad4a4f1151b096ad72019a6582db1f60fc/results/single_task/ViT-B-32/nonlinear_ft_accuracies.json

![image](https://github.com/user-attachments/assets/d53f9ce9-4a7a-4fe3-8e72-8686ad66808b)

It seems like the individual model's performance on the DTD test set is unexpectedly high. I'm curious as to why these are coming out this way. Could you explain the possible reasons for this?

Thank you.

**Comment by wang-kee** [comment]
Hi,

Thanks for your interest in our work.

We have noticed that there was a issue in generating the split of DTD test set. We refer to  https://github.com/mlfoundations/task_vectors/issues/1 for generating it. 

We will update our checkpoints soon with the updated model checkpoint and masks. 

Please feel free to let us know if there are anything else we could help you with.

**Comment by wang-kee** [comment]
Hi,

Please note that the checkpoints have already been updated. We have updated the Readme for how to download the new checkpoints from HuggingFace.

**Comment by kasurashan** [comment]
Thank you!
